controllers:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100
  robot_state_controller:
    type: robot_state_controller/RobotStateController
    publish_rate: 100

  left_a_controller:
    type: effort_controllers/JointVelocityController
    joint: "left_a_joint"
    pid: { p: 2.5, i: 0, d: 0.01, i_clamp_max: 0.0, i_clamp_min: -0.0, antiwindup: true, publish_state: true }
  right_a_controller:
    type: effort_controllers/JointVelocityController
    joint: "right_a_joint"
    pid: { p: 2.5, i: 0, d: 0.01, i_clamp_max: 0.0, i_clamp_min: -0.0, antiwindup: true, publish_state: true }
  yaw_controller:
    type: effort_controllers/JointPositionController
    joint: "yaw_joint"
    pid: { p: 2000000, i: 0, d: 1000, i_clamp_max: 0.4, i_clamp_min: -0.4, antiwindup: true, publish_state: true }
  trigger_controller:
    type: effort_controllers/JointPositionController
    joint: "trigger_joint"
    pid: { p: 15.0, i: 0, d: 0.8, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true, publish_state: true }
  b_controller:
    type: effort_controllers/JointPositionController
    joint: "b_joint"
    pid: { p: 0, i: 0, d: 0.0, i_clamp_max: 0.4, i_clamp_min: -0.4, antiwindup: true, publish_state: true }

  trigger_calibration_controller:
    type: rm_calibration_controllers/MechanicalCalibrationController
    joint: "trigger_joint"
    actuator: [ trigger_joint_motor ]
    velocity:
      search_velocity: -8.0
      vel_threshold: 0.02
      joint: trigger_joint
      pid: { p: 1.0, i: 0, d: 0.0, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true }

  left_a_calibration_controller:
    type: rm_calibration_controllers/MechanicalCalibrationController
    joint: left_a_joint
    actuator: [ left_a_joint_motor ]
    velocity:
      search_velocity: -5.0
      vel_threshold: 0.2
      joint: left_a_joint
      pid: { p: 0.3, i: 0, d: 0.0, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true }

  right_a_calibration_controller:
    type: rm_calibration_controllers/MechanicalCalibrationController
    joint: right_a_joint
    actuator: [ right_a_joint_motor ]
    velocity:
      search_velocity: -5.0
      vel_threshold: 0.2
      joint: right_a_joint
      pid: { p: 0.3, i: 0, d: 0.0, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true }

  b_calibration_controller:
    type: rm_calibration_controllers/MechanicalCalibrationController
    joint: b_joint
    actuator: [ b_joint_motor ]
    velocity:
      search_velocity: 0.005
      vel_threshold: 0.001
      joint: b_joint
      pid: { p: 0, i: 0, d: 0.0, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true }

  yaw_calibration_controller:
    type: rm_calibration_controllers/GpioCalibrationController
    joint: yaw_joint
    actuator: [ yaw_joint_motor ]
    gpio: "calibration_yaw"
    initial_gpio_state: false
    velocity:
      search_velocity: -8.0
      slow_forward_velocity:  -4.0
      joint: yaw_joint
      pid: { p: 185.0, i: 0, d: 0.0, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true }
    position:
      pos_threshold: 0.1
      backward_angle: -0.11
      joint: yaw_joint
      pid: { p: 2000000, i: 0, d: 1000, i_clamp_max: 0.4, i_clamp_min: -0.4, antiwindup: true, publish_state: true }


