can_motors:
  - can_id: 7
    can_bus: 0
    name: "left_a_joint_motor"
    type: "M3508"
    need_calibration: true
  - can_id: 3
    can_bus: 0
    name: "right_a_joint_motor"
    type: "M3508"
    need_calibration: true
  - can_id: 1
    can_bus: 0
    name: "trigger_joint_motor"
    type: "M2006"
    need_calibration: true
  - can_id: 8
    can_bus: 0
    name: "b_joint_motor"
    type: "GM6020"
    need_calibration: true
  - can_id: 6
    can_bus: 0
    name: "yaw_joint_motor"
    type: "GM6020"
    need_calibration: true

gpios:
  - name: "calibration_yaw"
    pin: 0
    mode: 0

dbus:
  - name: "dbus"
