can_motors:
  ############ can0 ############
  - can_id: 1
    can_bus: 0
    name: "left_diff_motor"
    type: "DM4310"
    need_calibration: false
  - can_id: 2
    can_bus: 0
    name: "right_diff_motor"
    type: "DM4310"
    need_calibration: false
  - can_id: 3
    can_bus: 0
    name: "joint4_motor"
    type: "DM4310"
    need_calibration: false
  ################ can1 ############
  - can_id: 1
    can_bus: 1
    name: "middle_pitch_joint_motor"
    type: "DM4340"
    need_calibration: false
  - can_id: 2
    can_bus: 1
    name: "joint3_motor"
    type: "DM4340"
    need_calibration: false
  - can_id: 3
    can_bus: 1
    name: "joint2_motor"
    type: "DM8009"
    need_calibration: false
################### gpio ###################
gpios:
  - name: "main_gripper"
    pin: 0
    mode: 1
  - name: "silver_gripper1"
    pin: 1
    mode: 1
  - name: "silver_gripper3"
    pin: 2
    mode: 1
  - name: "silver_pump"
    pin: 3
    mode: 1
  - name: "silver_gripper2"
    pin: 4
    mode: 1
  - name: "unused1"
    pin: 5
    mode: 1
  - name: "unused2"
    pin: 6
    mode: 1
  - name: "gold_gripper"
    pin: 7
    mode: 1
