dbus:
  - name: "dbus"
can_motors:
  - can_id: 1
    can_bus: 0
    name: "left_front_wheel_motor"
    type: "M3508"
    need_calibration: false
  - can_id: 2
    can_bus: 0
    name: "left_back_wheel_motor"
    type: "M3508"
    need_calibration: false
  - can_id: 3
    can_bus: 0
    name: "right_back_wheel_motor"
    type: "M3508"
    need_calibration: false
  - can_id: 4
    can_bus: 0
    name: "right_front_wheel_motor"
    type: "M3508"
    need_calibration: false
  - can_id: 5
    can_bus: 0
    name: "silver_lifter_joint_motor"
    type: "M3508"
    need_calibration: true
  ##############  can1 ##############
  - can_id: 1
    can_bus: 1
    name: "joint1_motor"
    type: "M3508"
    need_calibration: true
  - can_id: 2
    can_bus: 1
    name: "silver_pusher_joint_motor"
    type: "M2006"
    need_calibration: true
  - can_id: 3
    can_bus: 1
    name: "silver_rotator_joint_motor"
    type: "M3508"
    need_calibration: true
  - can_id: 4
    can_bus: 1
    name: "gold_pusher_joint_motor"
    type: "M2006"
    need_calibration: true
  - can_id: 5
    can_bus: 1
    name: "gold_lifter_joint_motor"
    type: "M3508"
    need_calibration: true
  - can_id: 6
    can_bus: 1
    name: "pitch_joint_motor"
    type: "GM6020"
    need_calibration: false
  - can_id: 7
    can_bus: 1
    name: "yaw_joint_motor"
    type: "GM6020"
    need_calibration: false
