camera:
  image_width: 1280
  image_height: 1024
  pixel_format: bgr8
  camera_info_url: ''
  camera_name: galaxy_6mm
  camera_frame_id: camera_optical_frame
  camera_sn: KE0220040170
  frame_rate: 1000
  exposure_auto: false
  exposure_value: 1600
  exposure_value_windmill: 3000
  gamma_selector: 2
  gamma_value: 0.5
  enable_imu_trigger: true
