ethercat_master:
  time_step: 0.001

ethercat_devices:
  - type: Rm
    name: Chassis
    configuration_file: device_configurations/hero2_chassis.yaml
    ethercat_bus: enp113s0
    ethercat_address: 2
  - type: Rm
    name: Gimbal
    configuration_file: device_configurations/hero2_gimbal.yaml
    ethercat_bus: enp113s0
    ethercat_address: 1
