rm_manual:
  robot_type: "dart2"
  dbus_topic: "/rm_ecat_hw/dbus"
  chassis_calibrate_motor: [ ]
  gimbal_calibrate_motor: [ "yaw_joint_motor" ]
  shooter_calibrate_motor: [ "trigger_joint_motor","left_a_joint_motor","right_a_joint_motor","b_joint_motor" ]

  launch_id: [1,2,3,4]

  dart_list:
    first_dart:
      id: 1
      param: [0.01, 0.0, 0.01, 0.0]
    second_dart:
      id: 2
      param: [0.01, 0.0, 0.01, 0.0]
    third_dart:
      id: 3
      param: [ 0.01, 0.0, 0.01, 0.0 ]
      #outpost:offset,qd//base:offset,qd
    fourth_dart:
      id: 4
      param: [ 0.01, 0.0, 0.01, 0.0]
      #outpost:offset,qd//base:offset,qd
    fifth_dart:
      id: 5
      param: [ 0.01, 368.0, -0.002, 0.0]
      #outpost:offset,qd//base:offset,qd
    sixth_dart:
      id: 6
      param: [ 0.01, 0.0, -0.0, 0.0 ]
      #outpost:offset,qd//base:offset,qd
    seventh_dart:
      id: 7
      param: [ 0.00, 415.0,-0.00, 506.0 ]
      #outpost:offset,qd//base:offset,qd
    eighth_dart:
      id: 8
      param: [ 0.00, 415.0, -0.002,440.5]
      #outpost:offset,qd//base:offset,qd
    ninth_dart:
      id: 9
      param: [ 0.000, 400.0, 0.002, 499.0]
      #outpost:offset,qd//base:offset,qd
    tenth_dart:
      id: 10
      param: [ 0.000, 400.0, -0.002, 501.0 ]

  targets:
    outpost:
      position: [0.01, 0.0]
    base:
      position: [ 0.01, 0.0]

  yaw:
    topic: "/controllers/yaw_controller/command"
    joint: "yaw_joint"
  a_left:
    topic: "/controllers/left_a_controller/command"
    joint: "left_a_joint"
    a_left_max: 17.16
    a_left_min: 0.5
    downward_vel: 3.0
    upward_vel: -6.0
  a_right:
    topic: "/controllers/right_a_controller/command"
    joint: "right_a_joint"
    a_right_max: 17.16
    a_right_min: 0.5
    downward_vel: 3.0
    upward_vel: -6.0
  trigger:
    topic: "/controllers/trigger_controller/command"
    joint: "trigger_joint"
    trigger_home: 0.6
    trigger_work: 0.09

  b:
    topic: "/controllers/b_controller/command"
    joint: "b_joint"

  controllers_list:
    state_controllers:
      - controllers/robot_state_controller
      - controllers/joint_state_controller
    main_controllers:
      - controllers/left_a_controller
      - controllers/right_a_controller
      - controllers/yaw_controller
      - controllers/trigger_controller
    calibration_controllers:
      - controllers/left_a_calibration_controller
      - controllers/right_a_calibration_controller
      - controllers/yaw_calibration_controller
      - controllers/trigger_calibration_controller
  shooter_calibration:
    - start_controllers:
        - controllers/trigger_calibration_controller
        - controllers/left_a_calibration_controller
        - controllers/right_a_calibration_controller
      stop_controllers:
        - controllers/trigger_controller
        - controllers/left_a_controller
        - controllers/right_a_controller
      services_name:
        - /controllers/trigger_calibration_controller/is_calibrated
        - /controllers/left_a_calibration_controller/is_calibrated
        - /controllers/right_a_calibration_controller/is_calibrated
  gimbal_calibration:
    - start_controllers:
        - controllers/yaw_calibration_controller
      stop_controllers:
        - controllers/yaw_controller
      services_name:
        - /controllers/yaw_calibration_controller/is_calibrated
