rm_manual:
  robot_type: "dart"
  dbus_topic: "/rm_ecat_hw/dbus"
  chassis_calibrate_motor: [ ]
  gimbal_calibrate_motor: [ "left_pitch_joint_motor","right_pitch_joint_motor","yaw_joint_motor" ]
  shooter_calibrate_motor: [ "trigger_joint_motor" ]

  launch_id: [1,2,5,4] #[ 74,77,79,80 ] #[74,79,73,77]
  trigger_position: [ 0.003251, 0.008298, 0.014457, 0.018 ]

  dart_list:
    first_dart:
      id: 1
      #param: [ 0.002, 393.0, 0.001, 503.5 ]
      param: [0.0, 400.0, 0.003, 432.0] #A
      #outpost:offset,qd//base:offset,qd
    second_dart:
      id: 2
      # param: [ 0.002, 405.0, 0.002, 503.0 ]
      param: [0.00, 385.0, 0.001, 440.0]  #
      #outpost:offset,qd//base:offset,qd
    third_dart:
      id: 3
      param: [ -0.006, 358.0, 0.00, 430.5 ]  #15
      #param: [0.00, 415.0, -0.002, 499.0]
      #outpost:offset,qd//base:offset,qd
    fourth_dart:
      id: 4
      param: [ -0.006, 368.0, -0.006, 439.5]  #14
      #param: [0.0035, 403.0, -0.003, 500.5]
      #outpost:offset,qd//base:offset,qd
    fifth_dart:
      id: 5
      #param: [ 0.00, 415.0,-0.001, 504.0]
      param: [-0.005, 368.0, -0.002, 443.5] #001k
      #outpost:offset,qd//base:offset,qd
    sixth_dart:
      id: 6
      param: [ -0.08, 420.0, -0.0, 502.0 ]
      #outpost:offset,qd//base:offset,qd
    seventh_dart:
      id: 7
      param: [ 0.00, 415.0,-0.00, 506.0 ]
      #param: [0.00, 415.0, -0.00, 504.5]
      #outpost:offset,qd//base:offset,qd
    eighth_dart:
      id: 8
      param: [ 0.00, 415.0, -0.002,440.5]
      #param: [ 0.00, 415.0, -0.002, 502.5]
      #outpost:offset,qd//base:offset,qd
    ninth_dart:
      id: 9
      # param: [0.000, 400.0, 0.002, 500.0 ]
      param: [ 0.000, 400.0, 0.002, 499.0]
      #outpost:offset,qd//base:offset,qd
    tenth_dart:
      id: 10
      param: [ 0.000, 400.0, -0.002, 501.0 ]

  targets:
    outpost:
      #normal -0.15895, 0.038539
      #red -0.168064, 0.062967 (第一发偏下一点，第二发偏下)
      #blue -0.16246, 0.061345（四中二）
#      position: [ -0.14643, 0.026645 ] #pitch yaw
      #position: [ -0.0040, 0.055 ] //raw
      position: [-0.0040, 0.1450] #中期
    base:
      #blue -0.003613, 0.26805 /0.26721
      #red -0.003613, 0.25191(偏左一点点，偏下一点点)
#      position: [ -0.003613, 0.2450 ] #house
      #position: [ -0.0040, 0.26650 ] #pitch yaw-0.003586, 0.2665
      position: [ -0.040, 0.1350  ] #中期

  left_pitch:
    topic: "/controllers/left_pitch_controller/command"
    scale: 0.04
    scale_micro: 0.0001
    joint: "left_pitch_joint"
  yaw:
    topic: "/controllers/yaw_controller/command"
    joint: "yaw_joint"
  friction_left:
    topic: "/controllers/left_friction_controller/command"
    joint: "left_friction_wheel_joint"
  friction_right:
    topic: "/controllers/right_friction_controller/command"
    joint: "right_friction_wheel_joint"
  trigger:
    topic: "/controllers/trigger_controller/command"
    joint: "trigger_joint"
    upward_vel: -0.003

  controllers_list:
    state_controllers:
      - controllers/robot_state_controller
      - controllers/joint_state_controller
    main_controllers:
      - controllers/left_pitch_controller
      - controllers/yaw_controller
      - controllers/left_friction_controller
      - controllers/right_friction_controller
      - controllers/trigger_controller
      - controllers/mimic_joint1_controller
    calibration_controllers:
      - controllers/left_pitch_calibration_controller
      - controllers/right_pitch_calibration_controller
      - controllers/yaw_calibration_controller
      - controllers/trigger_calibration_controller
  trigger_calibration:
    - start_controllers:
        - controllers/trigger_calibration_controller
      stop_controllers:
        - controllers/trigger_controller
      services_name:
        - /controllers/trigger_calibration_controller/is_calibrated
  gimbal_calibration:
    - start_controllers:
        - controllers/left_pitch_calibration_controller
        - controllers/right_pitch_calibration_controller
        - controllers/yaw_calibration_controller
      stop_controllers:
        - controllers/left_pitch_controller
        - controllers/mimic_joint1_controller
        - controllers/yaw_controller
      services_name:
        - /controllers/left_pitch_calibration_controller/is_calibrated
        - /controllers/right_pitch_calibration_controller/is_calibrated
        - /controllers/yaw_calibration_controller/is_calibrated
