rm_manual:
  dbus_topic: "/rm_ecat_hw/dbus"
  robot_type: "engineer2"
  chassis:
    topic: "/cmd_chassis"
    accel_x:
      - [ 200.0,8. ]
    accel_y:
      - [ 200.0,8. ]
    accel_z:
      - [ 200.0,30. ]
    safety_power: 400
    capacitor_threshold: 0.1
    charge_power: 0
    extra_power: 5000
    burst_power: 999
    buffer_threshold: 10
    power_gain: 0.85
    speed_scale: 0.8

    fast_speed_scale: 1.2
    normal_speed_scale: 0.6
    low_speed_scale: 0.3
    exchange_speed_scale: 0.15

    fast_gyro_scale: 1.5
    normal_gyro_scale: 0.8
    low_gyro_scale: 0.4
    exchange_gyro_scale: 0.2

  vel:
    topic: "/cmd_vel"
    max_linear_x:
      - [ 50.0,3. ]
      - [ 80.0,3. ]
      - [ 200.0,3. ]
    max_linear_y:
      - [ 50.0,3. ]
      - [ 80.0,3. ]
      - [ 200.0,3. ]
    max_angular_z:
      - [ 50.0,3. ]
      - [ 80.0,3. ]
      - [ 200.0,3. ]
    gyro_move_reduction: 1
    gyro_rotate_reduction: 1
  servo:
    topic: "/servo_server/delta_twist_cmds"
    max_linear_x: 0.4
    max_linear_y: 0.4
    max_linear_z: 0.4
    max_angular_x: 1.3
    max_angular_y: 1.3
    max_angular_z: 2.5
  gimbal:
    topic: "/controllers/gimbal_controller/command"
    max_yaw_vel: 2.5
    max_pitch_vel: 1
    gimbal_scale: 30
    track_timeout: 0.5
    finish_turning_threshold: 2.9
    target_cost_function:
      k_pos: 1.0
      k_vel: 1.0
      k_hp: 1.0
      k_freq: 1.0
      timeout: 0.0



  chassis_calibrate_motor: [ ]
  gimbal_calibrate_motor: [ ]
  shooter_calibrate_motor: [ ]

  controllers_list:
    state_controllers:
      - controllers/robot_state_controller
      - controllers/joint_state_controller
    main_controllers:
      - controllers/arm_trajectory_controller
      - controllers/chassis_controller
      - controllers/middle_pitch_controller
      - controllers/gimbal_controller
      - controllers/gpio_controller
      - controllers/silver_lifter_controller
      - controllers/silver_pusher_controller
      - controllers/silver_rotator_controller
      - controllers/gold_lifter_controller
      - controllers/gold_pusher_controller

    calibration_controllers:
      - controllers/joint1_calibration_controller
      - controllers/silver_lifter_calibration_controller
      - controllers/silver_pusher_calibration_controller
      - controllers/silver_rotator_calibration_controller
      - controllers/gold_pusher_calibration_controller
      - controllers/gold_lifter_calibration_controller

  calibration_gather:
    - start_controllers:
        - controllers/joint1_calibration_controller
        - controllers/silver_lifter_calibration_controller
        - controllers/silver_pusher_calibration_controller
        - controllers/silver_rotator_calibration_controller
        - controllers/gold_pusher_calibration_controller
        - controllers/gold_lifter_calibration_controller
      stop_controllers:
        - controllers/gimbal_controller
        - controllers/arm_trajectory_controller
        - controllers/silver_lifter_controller
        - controllers/silver_pusher_controller
        - controllers/silver_rotator_controller
        - controllers/gold_pusher_controller
        - controllers/gold_lifter_controller
      services_name:
        - /controllers/joint1_calibration_controller/is_calibrated
        - /controllers/silver_lifter_calibration_controller/is_calibrated
        - /controllers/silver_pusher_calibration_controller/is_calibrated
        - /controllers/silver_rotator_calibration_controller/is_calibrated
        - /controllers/gold_pusher_calibration_controller/is_calibrated
        - /controllers/gold_lifter_calibration_controller/is_calibrated
