rm_referee:
  robot_type: engineer2
  send_ui_queue_delay: 0.05
  add_ui_frequency: 0.5
  add_ui_max_times: 3
  dbus_topic: "/rm_ecat_hw/dbus"
  interactive_data:
  ui:
    trigger_change:
      - name: "servo_mode"
        config: { start_position: [ 50, 700 ], size: 15, width: 2, title: "mode:" }
    fixed:
      - name: "car_line_left"
        config: { type: "line", width: 2, color: "orange",
                  start_position: [ 887, 456 ], end_position: [ 626, 230 ] }
      - name: "car_line_right"
        config: { type: "line", width: 2, color: "orange",
                  start_position: [ 1047, 457 ], end_position: [ 1245, 245 ] }
    flash:
      - name: "engineer_action"
        data:
          - { flag: 1, config: { type: "line", width: 2, color: "orange",start_position: [ 1136, 179 ], end_position: [ 1233, 36 ] } }
          - { flag: 2, config: { type: "line", width: 2, color: "orange",start_position: [ 1047, 457 ], end_position: [ 1245, 245 ] } }
          - { flag: 2, config: { type: "line", width: 2, color: "orange",start_position: [ 887, 456 ], end_position: [ 626, 230 ] } }
